name: translation_manager
description: A translation managing package inspired by GetX
version: 1.0.0
homepage: https://github.com/edkluivert/translation_manager


environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  flutter_localization: ^0.3.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
